name: tests

on:
  pull_request:
    branches: ["master"]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install ruff black
      - run: ruff .
      - run: black --check .
